### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by sunlewuyou** [mkorthof/freenom-script#16]
Hello, can you optimize this script? It doesn't work properly on openwrt, which is very useful. Thanks !

**Comment by mkorthof** [comment]
What kind of optimization? Is there something specific not working?
What hardware/software are you running the script on and does it have a recent version of Bash?

I'm running it on a PC Engines APU SBC myself.

**Comment by pureair** [comment]
I have the same problem running this on my router.
Basically, on routers and other embedded devices, Busybox ash is used instead of full-featured bash. And ash does not support array. Moreover, other utilities in Busybox are lite version as well, for example, basename does not support -s option. I am aware of this because I tried to modify your code to run on my router, but I was stuck by the array problem (I‘m not professional coder). 
https://stackoverflow.com/questions/26091758/arrays-in-shell-script-not-bash

**Comment by mkorthof** [comment]
@pureair, @sunlewuyou
Exactly, the script requires bash for arrays, regexp's, param substitution and other 'bashisms'. I suspect it would take quite a bit of work to rewrite it. The script is really written for bash (thats why readme says its required).

Btw, I used to use poor mans array's in posix sh using 'dynamic vars' e.g. `myvar="var_$n"`and `eval`. But you also still need curl/sed/awk etc with flags the stripped busybox versions might not support.

Not really interested in rewriting for sh myself really. If I were ever to rewrite this mess, it would be in python :)
