### ISSUE TITLE
Invalid config file

### ISSUE THREAD

**Issue by ghost** [mkorthof/freenom-script#5]
```
pi@cauquepi:~ $ freenom.sh -c /home/pi/freenom.conf -l
/usr/local/bin/freenom.sh: line 28: [: : integer expression expected
/usr/local/bin/freenom.sh: line 125: source: -c: invalid option
source: usage: source filename [arguments]

Listing Domains and ID's...

/usr/local/bin/freenom.sh: line 193: [: : integer expression expected
/usr/local/bin/freenom.sh: line 223: [: : integer expression expected
^C
pi@cauquepi:~ $ freenom.sh -l -c /home/pi/freenom.conf
/usr/local/bin/freenom.sh: line 28: [: : integer expression expected
Error: invalid config specified

Listing Domains and ID's...

/usr/local/bin/freenom.sh: line 193: [: : integer expression expected
/usr/local/bin/freenom.sh: line 223: [: : integer expression expected
^C
```
I think no explanation is needed :P

also the integer expression expected, I think it's because of the `$debug -eq 1`?

**Comment by mkorthof** [comment]
Oops :) Thanks for reporting.

As a temp work around you could put your conf in /usr/local/bin/freenom.conf
Or, change the following line:
https://github.com/mkorthof/freenom-script/blob/984bc2efde355ac16991b9bf11fa933a0409dfee/freenom.sh#L124
to `scriptConf="$2"`

Since debug and other defaults are set in the conf, you're getting the "integer expression expected" errors.
I've added a couple more checks in the next version for extra robustness.

**Comment by ghost** [comment]
@mkorthof what I ended up doing is ^C and ^V'ing my config file to the start of the script. Hacky, but :man_shrugging:

**Comment by mkorthof** [comment]
should be fixed in latest version
