### ISSUE TITLE
incorrect Update domain a-record

### ISSUE THREAD

**Issue by ruocogito** [mkorthof/freenom-script#8]
Problem:
There is one a-record one my dimain
Set up freenom.conf as need.
Run
freenom.sh -u

Result: it add new record, not update old.

Reason:
Look img1 on double red line: recName and look single redLine it eq it with empty string $sd
Solve:
Look on img2
Now it succes update ip

PS: 
with default freenom_update_force="0" and freenom_update_ip="0" it (freenom.sh -u) nothing do

![img1](https://user-images.githubusercontent.com/50730877/57908001-4f3e9200-78c2-11e9-9686-6bd8deed5d56.PNG)
![img2](https://user-images.githubusercontent.com/50730877/57907998-4e0d6500-78c2-11e9-91e9-675de1dd9f3b.PNG)

**Comment by mkorthof** [comment]
Hi,

Thanks for your elaborate report.

Actually it should work anyway.
Since you are updating the apex domain it allows only 1 record to be added/modified.
The result should be OK and the log file should say "Update ip successful".

In this case the Subdomain is indeed empty ("$recName" / "$sd" is empty) and the script always did an 'addRecord' like you found out.
In the next version the if statement also checks "$freenom_domain_name" and will modify if record exists.

FYI:

`freenom_update_force="0"` set to "1"  updates record even if your ip did not change
`freenom_update_ip="0"` is used by "-u" which sets it to "1" overriding .conf
